// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: LibraryBackup.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// v1 payload behind the magic+version header (LibraryBackupEnvelope.swift).
// docs/features/library-backup.md
//
// field numbers are permanent - never reuse, never retype, only add.
// reserve a dropped field instead of letting its number get reassigned.
// that's what lets an old backup decode against a newer build with no
// version bump - the envelope version is only for changes this can't
// absorb (§4).
//
// everything nests inside LibraryBackup - SeriesEntry/ChapterEntry both
// collide with existing app types otherwise.
//
// regenerate: protoc --swift_out=. LibraryBackup.proto
// (brew install swift-protobuf for protoc-gen-swift). commit the
// generated .pb.swift too - no build-time codegen plugin wired up.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct LibraryBackup: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var exportedByAppVersion: String = String()

  /// unix seconds
  var exportedDate: Int64 = 0

  var series: [LibraryBackup.SeriesEntry] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated struct SeriesEntry: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var preferredTitle: String = String()

    /// Status.rawValue
    var status: String = String()

    var addedDate: Int64 = 0

    var lastReadDate: Int64 = 0

    /// Orientation.rawValue
    var orientation: String = String()

    var showAllChapters: Bool = false

    var showHalfChapters: Bool = false

    var origins: [LibraryBackup.SeriesEntry.OriginEntry] = []

    var tags: [String] = []

    var authors: [String] = []

    var collections: [String] = []

    var trackerLinks: [LibraryBackup.SeriesEntry.TrackerLink] = []

    /// advisory only - the model bundle a restore lands on may not be the
    /// one this was exported from (SeriesRecord.catalogId's own doc comment:
    /// "a title absent from v01 may exist in the next bundle"). a miss here
    /// is read the same as never-resolved, not an error
    var catalogID: Int64 {
      get {_catalogID ?? 0}
      set {_catalogID = newValue}
    }
    /// Returns true if `catalogID` has been explicitly set.
    var hasCatalogID: Bool {self._catalogID != nil}
    /// Clears the value of `catalogID`. Subsequent reads from it will return its default value.
    mutating func clearCatalogID() {self._catalogID = nil}

    var unknownFields = SwiftProtobuf.UnknownStorage()

    nonisolated struct OriginEntry: Sendable {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      var sourceSlug: String = String()

      var seriesSlug: String = String()

      var priority: Int32 = 0

      var chapters: [LibraryBackup.SeriesEntry.ChapterEntry] = []

      var unknownFields = SwiftProtobuf.UnknownStorage()

      init() {}
    }

    /// the full chapter row, not just its progress - a restore must not
    /// depend on the source still carrying the same chapter list later.
    /// everything here maps straight onto ChapterRecord's own columns,
    /// minus what is local only (id, originId, path - a downloaded file's
    /// path is device-local and CBZ export's concern, not this one's)
    nonisolated struct ChapterEntry: Sendable {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      var number: Double = 0

      var slug: String = String()

      var title: String = String()

      var url: String = String()

      /// LanguageCode.rawValue
      var language: String = String()

      /// name, portable - findOrCreate on import
      var scanlator: String = String()

      var publishedDate: Int64 = 0

      var addedDate: Int64 = 0

      var progress: Double = 0

      var lastReadDate: Int64 {
        get {_lastReadDate ?? 0}
        set {_lastReadDate = newValue}
      }
      /// Returns true if `lastReadDate` has been explicitly set.
      var hasLastReadDate: Bool {self._lastReadDate != nil}
      /// Clears the value of `lastReadDate`. Subsequent reads from it will return its default value.
      mutating func clearLastReadDate() {self._lastReadDate = nil}

      var unknownFields = SwiftProtobuf.UnknownStorage()

      init() {}

      fileprivate var _lastReadDate: Int64? = nil
    }

    /// the SeriesTrackerRecord snapshot, not just enough to identify the
    /// link - that row is deliberately denormalized so it renders fully
    /// (title, progress, status) with zero network access when the reader
    /// is signed out (docs/features/trackers.md: "No account table... the
    /// snapshot columns"). writing only the identity fields here would
    /// restore a link that shows blank until the next sync; writing the
    /// whole snapshot restores the same fully-rendered signed-out state the
    /// app already treats as normal
    nonisolated struct TrackerLink: Sendable {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      /// Tracker.rawValue
      var tracker: String = String()

      /// the media id
      var remoteID: Int64 = 0

      /// the list-entry id, needed to
      var remoteEntryID: Int64 {
        get {_remoteEntryID ?? 0}
        set {_remoteEntryID = newValue}
      }
      /// Returns true if `remoteEntryID` has been explicitly set.
      var hasRemoteEntryID: Bool {self._remoteEntryID != nil}
      /// Clears the value of `remoteEntryID`. Subsequent reads from it will return its default value.
      mutating func clearRemoteEntryID() {self._remoteEntryID = nil}

      /// resume push/pull after re-auth
      var remoteTitle: String = String()

      /// Status.rawValue - already the
      var remoteStatus: String {
        get {_remoteStatus ?? String()}
        set {_remoteStatus = newValue}
      }
      /// Returns true if `remoteStatus` has been explicitly set.
      var hasRemoteStatus: Bool {self._remoteStatus != nil}
      /// Clears the value of `remoteStatus`. Subsequent reads from it will return its default value.
      mutating func clearRemoteStatus() {self._remoteStatus = nil}

      /// app's own vocabulary, not the
      /// tracker's raw one
      /// (SeriesTrackerRecord.remoteStatus
      /// is Status?, not a raw string)
      var remoteProgress: Int32 = 0

      /// canonical 0-100
      var remoteScore: Int32 {
        get {_remoteScore ?? 0}
        set {_remoteScore = newValue}
      }
      /// Returns true if `remoteScore` has been explicitly set.
      var hasRemoteScore: Bool {self._remoteScore != nil}
      /// Clears the value of `remoteScore`. Subsequent reads from it will return its default value.
      mutating func clearRemoteScore() {self._remoteScore = nil}

      var totalChapters: Int32 {
        get {_totalChapters ?? 0}
        set {_totalChapters = newValue}
      }
      /// Returns true if `totalChapters` has been explicitly set.
      var hasTotalChapters: Bool {self._totalChapters != nil}
      /// Clears the value of `totalChapters`. Subsequent reads from it will return its default value.
      mutating func clearTotalChapters() {self._totalChapters = nil}

      var unknownFields = SwiftProtobuf.UnknownStorage()

      init() {}

      fileprivate var _remoteEntryID: Int64? = nil
      fileprivate var _remoteStatus: String? = nil
      fileprivate var _remoteScore: Int32? = nil
      fileprivate var _totalChapters: Int32? = nil
    }

    init() {}

    fileprivate var _catalogID: Int64? = nil
  }

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

nonisolated extension LibraryBackup: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "LibraryBackup"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}exported_by_app_version\0\u{3}exported_date\0\u{1}series\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.exportedByAppVersion) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.exportedDate) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.series) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.exportedByAppVersion.isEmpty {
      try visitor.visitSingularStringField(value: self.exportedByAppVersion, fieldNumber: 1)
    }
    if self.exportedDate != 0 {
      try visitor.visitSingularInt64Field(value: self.exportedDate, fieldNumber: 2)
    }
    if !self.series.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.series, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: LibraryBackup, rhs: LibraryBackup) -> Bool {
    if lhs.exportedByAppVersion != rhs.exportedByAppVersion {return false}
    if lhs.exportedDate != rhs.exportedDate {return false}
    if lhs.series != rhs.series {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension LibraryBackup.SeriesEntry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = LibraryBackup.protoMessageName + ".SeriesEntry"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}preferred_title\0\u{1}status\0\u{3}added_date\0\u{3}last_read_date\0\u{1}orientation\0\u{3}show_all_chapters\0\u{3}show_half_chapters\0\u{1}origins\0\u{1}tags\0\u{1}authors\0\u{1}collections\0\u{3}tracker_links\0\u{3}catalog_id\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.preferredTitle) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.status) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.addedDate) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.lastReadDate) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.orientation) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.showAllChapters) }()
      case 7: try { try decoder.decodeSingularBoolField(value: &self.showHalfChapters) }()
      case 8: try { try decoder.decodeRepeatedMessageField(value: &self.origins) }()
      case 9: try { try decoder.decodeRepeatedStringField(value: &self.tags) }()
      case 10: try { try decoder.decodeRepeatedStringField(value: &self.authors) }()
      case 11: try { try decoder.decodeRepeatedStringField(value: &self.collections) }()
      case 12: try { try decoder.decodeRepeatedMessageField(value: &self.trackerLinks) }()
      case 13: try { try decoder.decodeSingularInt64Field(value: &self._catalogID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.preferredTitle.isEmpty {
      try visitor.visitSingularStringField(value: self.preferredTitle, fieldNumber: 1)
    }
    if !self.status.isEmpty {
      try visitor.visitSingularStringField(value: self.status, fieldNumber: 2)
    }
    if self.addedDate != 0 {
      try visitor.visitSingularInt64Field(value: self.addedDate, fieldNumber: 3)
    }
    if self.lastReadDate != 0 {
      try visitor.visitSingularInt64Field(value: self.lastReadDate, fieldNumber: 4)
    }
    if !self.orientation.isEmpty {
      try visitor.visitSingularStringField(value: self.orientation, fieldNumber: 5)
    }
    if self.showAllChapters != false {
      try visitor.visitSingularBoolField(value: self.showAllChapters, fieldNumber: 6)
    }
    if self.showHalfChapters != false {
      try visitor.visitSingularBoolField(value: self.showHalfChapters, fieldNumber: 7)
    }
    if !self.origins.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.origins, fieldNumber: 8)
    }
    if !self.tags.isEmpty {
      try visitor.visitRepeatedStringField(value: self.tags, fieldNumber: 9)
    }
    if !self.authors.isEmpty {
      try visitor.visitRepeatedStringField(value: self.authors, fieldNumber: 10)
    }
    if !self.collections.isEmpty {
      try visitor.visitRepeatedStringField(value: self.collections, fieldNumber: 11)
    }
    if !self.trackerLinks.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.trackerLinks, fieldNumber: 12)
    }
    try { if let v = self._catalogID {
      try visitor.visitSingularInt64Field(value: v, fieldNumber: 13)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: LibraryBackup.SeriesEntry, rhs: LibraryBackup.SeriesEntry) -> Bool {
    if lhs.preferredTitle != rhs.preferredTitle {return false}
    if lhs.status != rhs.status {return false}
    if lhs.addedDate != rhs.addedDate {return false}
    if lhs.lastReadDate != rhs.lastReadDate {return false}
    if lhs.orientation != rhs.orientation {return false}
    if lhs.showAllChapters != rhs.showAllChapters {return false}
    if lhs.showHalfChapters != rhs.showHalfChapters {return false}
    if lhs.origins != rhs.origins {return false}
    if lhs.tags != rhs.tags {return false}
    if lhs.authors != rhs.authors {return false}
    if lhs.collections != rhs.collections {return false}
    if lhs.trackerLinks != rhs.trackerLinks {return false}
    if lhs._catalogID != rhs._catalogID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension LibraryBackup.SeriesEntry.OriginEntry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = LibraryBackup.SeriesEntry.protoMessageName + ".OriginEntry"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}source_slug\0\u{3}series_slug\0\u{1}priority\0\u{1}chapters\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.sourceSlug) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.seriesSlug) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.priority) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.chapters) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.sourceSlug.isEmpty {
      try visitor.visitSingularStringField(value: self.sourceSlug, fieldNumber: 1)
    }
    if !self.seriesSlug.isEmpty {
      try visitor.visitSingularStringField(value: self.seriesSlug, fieldNumber: 2)
    }
    if self.priority != 0 {
      try visitor.visitSingularInt32Field(value: self.priority, fieldNumber: 3)
    }
    if !self.chapters.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.chapters, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: LibraryBackup.SeriesEntry.OriginEntry, rhs: LibraryBackup.SeriesEntry.OriginEntry) -> Bool {
    if lhs.sourceSlug != rhs.sourceSlug {return false}
    if lhs.seriesSlug != rhs.seriesSlug {return false}
    if lhs.priority != rhs.priority {return false}
    if lhs.chapters != rhs.chapters {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension LibraryBackup.SeriesEntry.ChapterEntry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = LibraryBackup.SeriesEntry.protoMessageName + ".ChapterEntry"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}number\0\u{1}slug\0\u{1}title\0\u{1}url\0\u{1}language\0\u{1}scanlator\0\u{3}published_date\0\u{3}added_date\0\u{1}progress\0\u{3}last_read_date\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularDoubleField(value: &self.number) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.slug) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.title) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.url) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.language) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.scanlator) }()
      case 7: try { try decoder.decodeSingularInt64Field(value: &self.publishedDate) }()
      case 8: try { try decoder.decodeSingularInt64Field(value: &self.addedDate) }()
      case 9: try { try decoder.decodeSingularDoubleField(value: &self.progress) }()
      case 10: try { try decoder.decodeSingularInt64Field(value: &self._lastReadDate) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.number.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.number, fieldNumber: 1)
    }
    if !self.slug.isEmpty {
      try visitor.visitSingularStringField(value: self.slug, fieldNumber: 2)
    }
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 3)
    }
    if !self.url.isEmpty {
      try visitor.visitSingularStringField(value: self.url, fieldNumber: 4)
    }
    if !self.language.isEmpty {
      try visitor.visitSingularStringField(value: self.language, fieldNumber: 5)
    }
    if !self.scanlator.isEmpty {
      try visitor.visitSingularStringField(value: self.scanlator, fieldNumber: 6)
    }
    if self.publishedDate != 0 {
      try visitor.visitSingularInt64Field(value: self.publishedDate, fieldNumber: 7)
    }
    if self.addedDate != 0 {
      try visitor.visitSingularInt64Field(value: self.addedDate, fieldNumber: 8)
    }
    if self.progress.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.progress, fieldNumber: 9)
    }
    try { if let v = self._lastReadDate {
      try visitor.visitSingularInt64Field(value: v, fieldNumber: 10)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: LibraryBackup.SeriesEntry.ChapterEntry, rhs: LibraryBackup.SeriesEntry.ChapterEntry) -> Bool {
    if lhs.number != rhs.number {return false}
    if lhs.slug != rhs.slug {return false}
    if lhs.title != rhs.title {return false}
    if lhs.url != rhs.url {return false}
    if lhs.language != rhs.language {return false}
    if lhs.scanlator != rhs.scanlator {return false}
    if lhs.publishedDate != rhs.publishedDate {return false}
    if lhs.addedDate != rhs.addedDate {return false}
    if lhs.progress != rhs.progress {return false}
    if lhs._lastReadDate != rhs._lastReadDate {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension LibraryBackup.SeriesEntry.TrackerLink: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = LibraryBackup.SeriesEntry.protoMessageName + ".TrackerLink"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}tracker\0\u{3}remote_id\0\u{3}remote_entry_id\0\u{3}remote_title\0\u{3}remote_status\0\u{3}remote_progress\0\u{3}remote_score\0\u{3}total_chapters\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.tracker) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.remoteID) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self._remoteEntryID) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.remoteTitle) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._remoteStatus) }()
      case 6: try { try decoder.decodeSingularInt32Field(value: &self.remoteProgress) }()
      case 7: try { try decoder.decodeSingularInt32Field(value: &self._remoteScore) }()
      case 8: try { try decoder.decodeSingularInt32Field(value: &self._totalChapters) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.tracker.isEmpty {
      try visitor.visitSingularStringField(value: self.tracker, fieldNumber: 1)
    }
    if self.remoteID != 0 {
      try visitor.visitSingularInt64Field(value: self.remoteID, fieldNumber: 2)
    }
    try { if let v = self._remoteEntryID {
      try visitor.visitSingularInt64Field(value: v, fieldNumber: 3)
    } }()
    if !self.remoteTitle.isEmpty {
      try visitor.visitSingularStringField(value: self.remoteTitle, fieldNumber: 4)
    }
    try { if let v = self._remoteStatus {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    if self.remoteProgress != 0 {
      try visitor.visitSingularInt32Field(value: self.remoteProgress, fieldNumber: 6)
    }
    try { if let v = self._remoteScore {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._totalChapters {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 8)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: LibraryBackup.SeriesEntry.TrackerLink, rhs: LibraryBackup.SeriesEntry.TrackerLink) -> Bool {
    if lhs.tracker != rhs.tracker {return false}
    if lhs.remoteID != rhs.remoteID {return false}
    if lhs._remoteEntryID != rhs._remoteEntryID {return false}
    if lhs.remoteTitle != rhs.remoteTitle {return false}
    if lhs._remoteStatus != rhs._remoteStatus {return false}
    if lhs.remoteProgress != rhs.remoteProgress {return false}
    if lhs._remoteScore != rhs._remoteScore {return false}
    if lhs._totalChapters != rhs._totalChapters {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
